# Generated by Django 4.1.2 on 2022-10-16 15:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['Name']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['Date']},
        ),
        migrations.RemoveField(
            model_name='command',
            name='Symbol',
        ),
        migrations.AlterField(
            model_name='match',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField()),
                ('Command', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Command', to='Tracker.command')),
                ('Match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Match', to='Tracker.match')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Amount'],
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='BetForOne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BetForOne', to='Tracker.bet'),
        ),
        migrations.AlterField(
            model_name='match',
            name='BetForTwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BetForTwo', to='Tracker.bet'),
        ),
    ]
