# Generated by Django 4.1.2 on 2022-10-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_alter_bet_command_alter_bet_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='Players',
        ),
        migrations.AddField(
            model_name='player',
            name='PlayerCommand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PlayerCommand', to='Tracker.command'),
        ),
    ]
