# Generated by Django 4.1.2 on 2022-10-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_alter_bet_user'),
    ]

    operations = [

    ]
