# Generated by Django 4.1.2 on 2022-10-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0011_bet_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='CommandOne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CommandOne', to='Tracker.command'),
        ),
        migrations.AlterField(
            model_name='match',
            name='CommandTwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CommandTwo', to='Tracker.command'),
        ),
    ]
