# Generated by Django 4.1.2 on 2022-10-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0012_alter_command_name_alter_match_commandone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Winner', to='Tracker.command'),
        ),
    ]
