# Generated by Django 4.1.2 on 2022-10-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0013_alter_match_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id']},
        ),
    ]
